# Generated by Django 5.0.2 on 2024-04-19 08:22

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_userorder_phone_alter_userorder_address1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='phone',
        ),
        migrations.AddField(
            model_name='userorder',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(null='true'),
            preserve_default='true',
        ),
    ]
