# Generated by Django 5.0.2 on 2024-04-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('rebateQuantity', models.SmallIntegerField()),
                ('rebatePercent', models.FloatField()),
                ('img', models.URLField()),
            ],
        ),
    ]
