# Generated by Django 5.0.2 on 2024-04-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='img',
        ),
    ]
