# Generated by Django 5.0.2 on 2024-04-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_remove_items_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('img', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
